FROM ubuntu:latest
MAINTAINER your_name "cjh66944@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python3-pip python-dev build-essential 
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["app.py"]
